import { defineConfig, type Plugin } from 'vite'
import { createHash } from 'node:crypto'
import { readdirSync } from 'node:fs'
import { join } from 'node:path'

// This is the v2 preview repo: its Project Pages live under
// https://silentkinfolk.github.io/watchthedrift-dev/ (production is the sibling
// /watchthedrift/), so every emitted asset URL must be prefixed with this repo name.
export default defineConfig({
  base: '/watchthedrift-dev/',
  build: {
    // Keep the corner model (`src/models/*`, imported `?url`) as real hashed files,
    // never inlined as data URIs. The manifest is only ~3 KB — under Vite's default
    // 4 KB inline limit — but inlining it would bury the model inside the JS bundle,
    // where the service worker can't precache it as its own asset and the clean
    // "model is a versioned same-origin file" story (issue #13) breaks. Everything
    // else keeps the default size-based inlining.
    assetsInlineLimit: (filePath) => (filePath.includes('/models/') ? false : undefined),
  },
  plugins: [serviceWorker()],
})

/**
 * Hand-rolled offline service worker (issue #13). No Workbox / vite-plugin-pwa: that
 * pulls a heavy dependency this minimal, hand-rolled-everything repo (we wrote our own
 * inference kernel rather than ship onnxruntime) doesn't want. Instead, at build we
 * already know every emitted filename, so we precache the exact set and ship a tiny SW.
 *
 * The precache list is the app shell + ALL hashed assets (JS, CSS, and the ?url corner
 * model) + the public PWA passthrough (manifest + icons). Because the asset filenames
 * are content-hashed, they already encode app + model content: any change to either
 * rotates the cache name, so the SW reinstalls and the new app+model land together —
 * the atomic app+model versioning PLAN's Infra track asks for, for free.
 */
function serviceWorker(): Plugin {
  let base = '/'
  let publicDir: string | false = false
  return {
    name: 'wtd-service-worker',
    apply: 'build',
    configResolved(cfg) {
      base = cfg.base
      publicDir = cfg.publicDir
    },
    generateBundle(_opts, bundle) {
      const emitted = Object.keys(bundle).filter((f) => !f.endsWith('.map')) // skip sourcemaps
      const publicFiles = publicDir ? listFiles(publicDir) : [] // manifest + icons
      const urls = unique([
        base, // start_url (manifest start_url ".")
        `${base}index.html`,
        ...emitted.map((f) => base + f),
        ...publicFiles.map((f) => base + f),
      ])
      // Content-addressed cache name — see the doc comment above. Sort so the hash is
      // order-independent across builds.
      const version = createHash('sha256').update([...urls].sort().join('\n')).digest('hex').slice(0, 12)
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: renderServiceWorker(urls, version, base) })
    },
  }
}

/** Recursively list files under `dir` as forward-slash relative paths (URL-ready). */
function listFiles(dir: string, prefix = ''): string[] {
  const out: string[] = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name
    if (entry.isDirectory()) out.push(...listFiles(join(dir, entry.name), rel))
    else if (entry.isFile()) out.push(rel)
  }
  return out
}

function unique(xs: string[]): string[] {
  return [...new Set(xs)]
}

/** The emitted sw.js. Plain browser JS (no bundling) with the precache list + cache
 *  name baked in. Cache-first for the same-origin shell/model (→ offline reading); the
 *  network time sources are deliberately left untouched so offline they fail honestly
 *  and the app says "connect to measure" instead of serving a stale time. */
function renderServiceWorker(urls: string[], version: string, base: string): string {
  return `// Generated by vite.config.ts (wtd-service-worker) — do not edit by hand.
const CACHE = 'wtd-${version}'
const PRECACHE = ${JSON.stringify(urls)}
const SHELL = ${JSON.stringify(`${base}index.html`)}

self.addEventListener('install', (event) => {
  // Precache the app shell + model so reading works offline; activate without waiting.
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()))
})

self.addEventListener('activate', (event) => {
  // Drop superseded versions (old app/model), then take control of open pages.
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && k.startsWith('wtd-')).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  // Only same-origin GETs are cacheable. Everything else goes straight to the network,
  // UNTOUCHED — above all the time sources (cross-origin timeapi.io / cloudflare, and
  // the same-origin HEAD Date-header probe): offline they must FAIL, so the app reports
  // "connect to measure" rather than measuring against a stale/cached time.
  if (req.method !== 'GET') return
  if (new URL(req.url).origin !== self.location.origin) return
  if (req.cache === 'no-store') return // belt-and-suspenders: never serve a no-store probe from cache

  // Cache-first: the precached shell + model answer instantly and work offline; anything
  // else falls back to the network and is cached for next time. An offline navigation to
  // an uncached path falls back to the cached app shell.
  event.respondWith(
    caches.match(req).then((hit) => {
      if (hit) return hit
      return fetch(req)
        .then((res) => {
          if (res.ok && res.type === 'basic') {
            const copy = res.clone()
            caches.open(CACHE).then((c) => c.put(req, copy))
          }
          return res
        })
        .catch(() => (req.mode === 'navigate' ? caches.match(SHELL) : Response.error())),
    ),
  )
})
`
}
