// Service-worker source generation (issue #13), kept here (pure, no fs) so it can be
// unit-tested — the emitted sw.js is hand-written JS in a template string, and a brace
// mismatch there fails SILENTLY in the browser (the SW throws at evaluation, goes
// redundant, and the app just… has no offline), which a syntax test catches at build.
// vite.config.ts walks dist/ + public/ for the file list and calls these.

import { createHash } from 'node:crypto'

/** Dedupe while preserving first-seen order. */
export function uniqueUrls(xs) {
  return [...new Set(xs)]
}

/**
 * Content-addressed cache name. The precache URLs include the content-HASHED asset
 * filenames (JS/CSS + the ?url model), so any app/model change rotates this name →
 * the SW reinstalls and the new app+model activate together (atomic app+model
 * versioning, PLAN Infra). Sorted so it's stable regardless of list order.
 */
export function cacheName(urls) {
  const h = createHash('sha256').update([...urls].sort().join('\n')).digest('hex').slice(0, 12)
  return `wtd-${h}`
}

/**
 * Render the sw.js source. Cache-first for the same-origin shell + model (→ offline
 * reading); the time sources are deliberately left untouched so offline they fail
 * honestly and the app says "connect to measure" instead of serving a stale time.
 * @param {string[]} urls   precache list (already base-prefixed + deduped)
 * @param {string} cache    cache name from cacheName()
 * @param {string} base     Vite base, e.g. '/watchthedrift-dev/' (ends with '/')
 */
export function renderServiceWorker(urls, cache, base) {
  return `// Generated by vite.config.ts (wtd-service-worker) — do not edit by hand.
const CACHE = ${JSON.stringify(cache)}
const PRECACHE = ${JSON.stringify(urls)}
const SHELL = ${JSON.stringify(`${base}index.html`)}

self.addEventListener('install', (event) => {
  // Precache the app shell + model so reading works offline; activate without waiting.
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()))
})

self.addEventListener('activate', (event) => {
  // Drop superseded versions (old app/model), then take control of open pages.
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE && k.startsWith('wtd-')).map((k) => caches.delete(k))),
    ).then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  // Only same-origin GETs are cacheable. Everything else goes straight to the network,
  // UNTOUCHED — above all the time sources (cross-origin timeapi.io / cloudflare, and
  // the same-origin HEAD Date-header probe): offline they must FAIL, so the app reports
  // "connect to measure" rather than measuring against a stale/cached time.
  if (req.method !== 'GET') return
  if (new URL(req.url).origin !== self.location.origin) return
  if (req.cache === 'no-store') return // belt-and-suspenders: never serve a no-store probe from cache

  // Cache-first: the precached shell + model answer instantly and work offline; anything
  // else falls back to the network and is cached for next time. An offline navigation to
  // an uncached path falls back to the cached app shell.
  //
  // ignoreVary is essential: static hosts (GitHub Pages, vite preview) serve the gzipped
  // JS/CSS with "Vary: Accept-Encoding", and without ignoreVary caches.match misses them
  // whenever the request's Accept-Encoding differs from precache time — so offline the
  // app shell would load but its scripts would 404 from cache. (The uncompressed model
  // .bin/.json carry no Vary, which is why they'd match either way.)
  const opts = { ignoreVary: true }
  event.respondWith(
    caches.match(req, opts).then((hit) => {
      if (hit) return hit
      return fetch(req).then((res) => {
        if (res.ok && res.type === 'basic') caches.open(CACHE).then((c) => c.put(req, res.clone()))
        return res
      }).catch(() => (req.mode === 'navigate' ? caches.match(SHELL, opts) : Response.error()))
    }),
  )
})
`
}
